# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar_doppler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SARDopplerExtraMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarization', models.CharField(default=b'', max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sar_doppler.Dataset')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sardopplerextrametadata',
            unique_together=set([('dataset', 'polarization')]),
        ),
    ]
